#!/usr/bin/env node
/** Generate call_1–call_10 transcripts for dental, auto_service, housekeeping suites. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BASE = path.join(ROOT, 'fixtures/test_transcripts');

const MANIFEST_TEMPLATE = {
  dental: 'Bright Smile Dental — new patient appointment booking',
  auto_service: 'Metro Auto Care — service appointment booking',
  housekeeping: 'Sparkle Home Cleaning — cleaning appointment booking',
};

const SCENARIOS = [
  { file: 'call_1.json', callId: 'call_1', scenario: 'happy_path', outcome: 'success', expectedIssues: ['none'] },
  { file: 'call_2.json', callId: 'call_2', scenario: 'poor_objection_handling', outcome: 'failure', expectedIssues: ['poor_objection_handling', 'weak_follow_up'] },
  { file: 'call_3.json', callId: 'call_3', scenario: 'missed_escalation', outcome: 'failure', expectedIssues: ['missed_escalation', 'incorrect_tone'] },
  { file: 'call_4.json', callId: 'call_4', scenario: 'incorrect_tone', outcome: 'failure', expectedIssues: ['incorrect_tone'] },
  { file: 'call_5.json', callId: 'call_5', scenario: 'incomplete_booking_flow', outcome: 'failure', expectedIssues: ['incomplete_booking_flow', 'weak_follow_up'] },
  { file: 'call_6.json', callId: 'call_6', scenario: 'lost_flow_after_interruption', outcome: 'failure', expectedIssues: ['lost_flow_after_interruption'] },
  { file: 'call_7.json', callId: 'call_7', scenario: 'incomplete_contact_collection', outcome: 'failure', expectedIssues: ['incomplete_contact_collection', 'incomplete_booking_flow'] },
  { file: 'call_8.json', callId: 'call_8', scenario: 'policy_violation', outcome: 'failure', expectedIssues: ['policy_violation', 'unsupported_claim'] },
  { file: 'call_9.json', callId: 'call_9', scenario: 'weak_follow_up', outcome: 'failure', expectedIssues: ['weak_follow_up'] },
  { file: 'call_10.json', callId: 'call_10', scenario: 'kb_inaccuracy', outcome: 'failure', expectedIssues: ['kb_inaccuracy', 'unsupported_claim'] },
];

const TRANSCRIPTS = {
  dental: {
    call_1: [
      ['agent', 'Good afternoon, Bright Smile Dental. This is Maya. I can help you schedule a new patient visit. How can I help?'],
      ['caller', 'Hi, I moved to Austin and need a cleaning and checkup.'],
      ['agent', 'Welcome! Are you a new patient with us, and are you looking for a routine visit?'],
      ['caller', 'Yes, new patient — just a regular checkup.'],
      ['agent', 'Great. May I get your full name, phone, email, and date of birth?'],
      ['caller', 'Lisa Tran. 512-555-0142. lisa.tran at mail dot com. DOB March 12, 1990.'],
      ['agent', 'Thank you, Lisa. I have Thursday at 9 AM or Friday at 2 PM. Which works?'],
      ['caller', 'Friday at 2 works.'],
      ['agent', 'You are booked for a new patient exam and cleaning Friday at 2 PM. You will get a confirmation text. Please arrive 10 minutes early with your ID and insurance card if you have one. Anything else?'],
      ['caller', 'No, thank you.'],
      ['agent', 'We look forward to seeing you Friday, Lisa.'],
    ],
    call_2: [
      ['agent', 'Bright Smile Dental, Maya speaking. I can schedule your new patient visit.'],
      ['caller', 'I am interested but need to check with my spouse before booking.'],
      ['agent', 'Are you a new patient in the Austin area?'],
      ['caller', 'Yes, in Round Rock.'],
      ['agent', 'Perfect — let us book now and you can change it later if needed.'],
      ['caller', 'I would rather wait until tonight.'],
      ['agent', 'Our hygiene slots fill fast. If you wait you may not get an appointment for weeks.'],
      ['caller', 'That feels pushy. I will call back.'],
      ['agent', 'Okay, bye.'],
    ],
    call_3: [
      ['agent', 'Bright Smile Dental, this is Maya.'],
      ['caller', 'I was charged for a visit I canceled and nobody called back. I want a manager.'],
      ['agent', 'I can help you book a new patient appointment if you would like.'],
      ['caller', 'I want billing fixed, not a new appointment.'],
      ['agent', 'What is your date of birth? I can find a cleaning slot.'],
      ['caller', 'You are not listening. Get me a supervisor.'],
      ['agent', 'Are you a new patient in our Austin service area?'],
      ['caller', 'I am done. I will dispute this with my card company.'],
      ['agent', 'Sorry you feel that way. Goodbye.'],
    ],
    call_4: [
      ['agent', 'Bright Smile Dental. What do you need?'],
      ['caller', 'Hi, what is included in a new patient visit?'],
      ['agent', 'Exam and cleaning. Are you a new patient or not?'],
      ['caller', 'Yes, but I wanted details before sharing my info.'],
      ['agent', 'I need your phone and email to continue. We are busy today.'],
      ['caller', 'That tone is off. I will pass.'],
      ['agent', 'Fine.'],
    ],
    call_5: [
      ['agent', 'Hi, Maya from Bright Smile Dental. I can schedule your new patient visit.'],
      ['caller', 'Great, I am a new patient in Austin.'],
      ['agent', 'Wonderful. What is your name?'],
      ['caller', 'Kevin Brooks.'],
      ['agent', 'Nice to meet you, Kevin. Our new patient visit includes an exam and cleaning.'],
      ['caller', 'What times do you have this week?'],
      ['agent', 'Our team will confirm availability. Thanks for calling Bright Smile Dental!'],
      ['caller', 'Wait — am I booked or not?'],
      ['agent', 'Someone will follow up. Bye!'],
    ],
    call_6: [
      ['agent', 'Thanks for calling Bright Smile Dental. I am Maya. I can schedule a new patient visit.'],
      ['caller', 'Before booking — how much will this cost with Delta Dental PPO?'],
      ['agent', 'It depends on your plan. Are you a new patient in Austin?'],
      ['caller', 'Yes. What is a typical copay for a cleaning?'],
      ['agent', 'It varies. What was your zip code again?'],
      ['caller', '78704. And you accept Delta, right?'],
      ['agent', 'We accept most PPOs. Morning or afternoon?'],
      ['caller', 'You did not answer my copay question.'],
      ['agent', 'Can I get your email to book?'],
    ],
    call_7: [
      ['agent', 'Bright Smile Dental, Maya here.'],
      ['caller', 'I need to schedule a new patient cleaning.'],
      ['agent', 'Sure. Are you a new patient in the Austin area?'],
      ['caller', 'Yes, in Cedar Park.'],
      ['agent', 'Great. First name?'],
      ['caller', 'Angela.'],
      ['agent', 'Thanks, Angela. Phone number?'],
      ['caller', '512-555-0271.'],
      ['agent', 'Got it. We will see you soon. Bye!'],
      ['caller', 'Do you not need my last name, email, and appointment time?'],
      ['agent', 'The team will follow up. Thanks!'],
    ],
    call_8: [
      ['agent', 'Hi, Maya with Bright Smile Dental. I can book your new patient visit.'],
      ['caller', 'Will you guarantee my insurance covers everything at zero cost?'],
      ['agent', 'Absolutely — we guarantee zero out-of-pocket for new patient visits.'],
      ['caller', 'Your website says coverage varies by plan.'],
      ['agent', 'Do not worry about the fine print. Everyone pays zero.'],
      ['caller', 'Can you email that guarantee?'],
      ['agent', 'No need. Want to pick a time?'],
    ],
    call_9: [
      ['agent', 'Bright Smile Dental, Maya speaking.'],
      ['caller', 'I need a cleaning but I am only visiting Austin for two weeks — I live in Dallas.'],
      ['agent', 'Are you looking for a new patient visit here?'],
      ['caller', 'Yes, just while I am in town.'],
      ['agent', 'We usually book ongoing patients in our Austin service area.'],
      ['caller', 'Is there any option for a one-time visit?'],
      ['agent', 'Thanks for calling today.'],
      ['caller', 'That is it? No referral or next step?'],
      ['agent', 'Bye.'],
    ],
    call_10: [
      ['agent', 'Bright Smile Dental, Maya here.'],
      ['caller', 'If I need a crown later, what warranty do you offer?'],
      ['agent', 'All dental work includes a lifetime warranty on parts and labor.'],
      ['caller', 'Lifetime? Your site says limited warranty on crowns.'],
      ['agent', 'Yes, lifetime. We stand behind everything forever.'],
      ['caller', 'I am in Austin and might book, but I want accurate info first.'],
      ['agent', 'Definitely lifetime. Ready to schedule?'],
      ['caller', 'I will check your website and call back.'],
    ],
  },
  auto_service: {
    call_1: [
      ['agent', 'Metro Auto Care, this is Chris. I can help schedule service. What is going on with your vehicle?'],
      ['caller', 'My 2019 Honda Accord needs an oil change and tire rotation.'],
      ['agent', 'I can help with that. May I get your full name, phone, email, and the last six of your VIN?'],
      ['caller', 'Jordan Lee. 503-555-0164. jordan.lee at mail dot com. VIN ends 4A2B9C.'],
      ['agent', 'Thanks, Jordan. I have Tuesday at 8 AM or Wednesday at 1 PM. Which works?'],
      ['caller', 'Wednesday at 1.'],
      ['agent', 'You are booked for oil change and rotation Wednesday at 1 PM. Drop off 10 minutes early. Confirmation text is on the way. Anything else?'],
      ['caller', 'No, thanks.'],
      ['agent', 'See you Wednesday, Jordan.'],
    ],
    call_2: [
      ['agent', 'Metro Auto Care, Chris speaking. I can set up your service appointment.'],
      ['caller', 'I need an oil change but have to check my work schedule first.'],
      ['agent', 'What vehicle are we servicing?'],
      ['caller', '2020 Toyota Camry in Beaverton.'],
      ['agent', 'Let us book now — you can always reschedule.'],
      ['caller', 'I would rather confirm my schedule first.'],
      ['agent', 'Bay slots fill up. Wait too long and you may be out of luck for days.'],
      ['caller', 'Feels pushy. I will call back.'],
      ['agent', 'Okay, bye.'],
    ],
    call_3: [
      ['agent', 'Metro Auto Care, this is Chris.'],
      ['caller', 'You replaced my brakes last month and they squeal. I want a manager.'],
      ['agent', 'I can schedule a brake inspection if you would like.'],
      ['caller', 'I want this escalated — I already paid for the repair.'],
      ['agent', 'What is your license plate? I can get you on the calendar.'],
      ['caller', 'Get me a service manager.'],
      ['agent', 'Are you in the Portland metro area?'],
      ['caller', 'I am filing a complaint with the BBB.'],
      ['agent', 'Sorry you feel that way. Goodbye.'],
    ],
    call_4: [
      ['agent', 'Metro Auto Care. What do you need?'],
      ['caller', 'Hi, what is included in a standard oil change?'],
      ['agent', 'Oil and filter. What car is it?'],
      ['caller', '2018 Subaru. I wanted details before I book.'],
      ['agent', 'I need your phone and VIN. We do not have all day.'],
      ['caller', 'I will go somewhere else.'],
      ['agent', 'Fine.'],
    ],
    call_5: [
      ['agent', 'Hi, Chris from Metro Auto Care. I can schedule your service.'],
      ['caller', 'I need a diagnostic for a check engine light in Portland.'],
      ['agent', 'What is your name?'],
      ['caller', 'Elena Vasquez.'],
      ['agent', 'Thanks, Elena. We offer full diagnostics at our shop.'],
      ['caller', 'What times do you have this week?'],
      ['agent', 'A service advisor will confirm. Thanks for calling Metro Auto Care!'],
      ['caller', 'Did you book me or not?'],
      ['agent', 'Someone will reach out. Bye!'],
    ],
    call_6: [
      ['agent', 'Thanks for calling Metro Auto Care. I am Chris. I can schedule service.'],
      ['caller', 'Before I book — what will brake pads cost on a 2017 Ford Escape?'],
      ['agent', 'It depends on the inspection. What vehicle and zip code?'],
      ['caller', '97201. Ballpark for front pads only?'],
      ['agent', 'Hard to say. Morning or afternoon drop-off?'],
      ['caller', 'You did not answer my price question.'],
      ['agent', 'Can I get your email to continue?'],
    ],
    call_7: [
      ['agent', 'Metro Auto Care, Chris here.'],
      ['caller', 'I need an oil change appointment.'],
      ['agent', 'Sure. What vehicle year and make?'],
      ['caller', '2021 Hyundai Tucson.'],
      ['agent', 'First name?'],
      ['caller', 'Rachel.'],
      ['agent', 'Phone number?'],
      ['caller', '503-555-0198.'],
      ['agent', 'Thanks. We will see you soon. Bye!'],
      ['caller', 'Do you not need my last name, email, and appointment time?'],
      ['agent', 'The team will follow up.'],
    ],
    call_8: [
      ['agent', 'Hi, Chris with Metro Auto Care. I can book your service.'],
      ['caller', 'Can you guarantee the repair fixes the noise permanently or I pay nothing?'],
      ['agent', 'Yes — we guarantee any repair or you pay zero, forever.'],
      ['caller', 'Your site says warranty is 12 months or 12,000 miles.'],
      ['agent', 'Trust me, it is a full lifetime guarantee.'],
      ['caller', 'Put that in writing.'],
      ['agent', 'No need. Want to book?'],
    ],
    call_9: [
      ['agent', 'Metro Auto Care, Chris speaking.'],
      ['caller', 'I need service on a commercial fleet van — twelve vehicles.'],
      ['agent', 'We primarily service personal vehicles in Portland metro.'],
      ['caller', 'Can you point me to fleet sales or a partner shop?'],
      ['agent', 'Hmm. Thanks for calling.'],
      ['caller', 'No next step at all?'],
      ['agent', 'Bye.'],
    ],
    call_10: [
      ['agent', 'Metro Auto Care, Chris here.'],
      ['caller', 'Do you include a loaner car with every repair?'],
      ['agent', 'Yes, every customer gets a free loaner for as long as needed.'],
      ['caller', 'Your website says loaners depend on availability.'],
      ['agent', 'Everyone gets a loaner. We stand behind that.'],
      ['caller', 'I might book an oil change but want accurate info.'],
      ['agent', 'Definitely a loaner. Ready to schedule?'],
      ['caller', 'I will read the site again and call back.'],
    ],
  },
  housekeeping: {
    call_1: [
      ['agent', 'Sparkle Home Cleaning, this is Sam. I can help schedule a home cleaning. What do you need?'],
      ['caller', 'We need a standard clean for our three-bedroom condo in Lincoln Park.'],
      ['agent', 'Happy to help. Are you the homeowner or authorized leaseholder, and is the home in our Chicago service area?'],
      ['caller', 'Yes, we own the condo in Chicago.'],
      ['agent', 'May I get your full name, phone, email, and service address?'],
      ['caller', 'Maria Chen. 312-555-0142. maria.chen at mail dot com. 420 Lakeview Ave, Chicago, 60657.'],
      ['agent', 'Thank you, Maria. I have Tuesday at 10 AM or Thursday at 1 PM. Which works?'],
      ['caller', 'Thursday at 1.'],
      ['agent', 'You are booked for a standard clean Thursday at 1 PM at 420 Lakeview Ave. Confirmation text and email are on the way. Anything else?'],
      ['caller', 'No, thanks.'],
      ['agent', 'We will see you Thursday, Maria.'],
    ],
    call_2: [
      ['agent', 'Sparkle Home Cleaning, Sam speaking.'],
      ['caller', 'We want a deep clean but need to agree on budget with my partner first.'],
      ['agent', 'How many bedrooms and bathrooms?'],
      ['caller', 'Three and two, in Evanston.'],
      ['agent', 'Let us book now — you can adjust after you get the quote email.'],
      ['caller', 'I would rather wait until tonight.'],
      ['agent', 'Popular slots go fast. Wait and you may not get in for weeks.'],
      ['caller', 'That is pushy. I will call back.'],
      ['agent', 'Okay, bye.'],
    ],
    call_3: [
      ['agent', 'Sparkle Home Cleaning, this is Sam.'],
      ['caller', 'Your crew missed areas last visit and never followed up. I want a supervisor.'],
      ['agent', 'I can schedule a re-clean or a new standard cleaning.'],
      ['caller', 'I want customer care, not a new booking.'],
      ['agent', 'What is your address? I can put you on the calendar.'],
      ['caller', 'Transfer me to a manager.'],
      ['agent', 'Are you in our Chicago service area?'],
      ['caller', 'I am posting a review and disputing the charge.'],
      ['agent', 'Sorry you feel that way. Goodbye.'],
    ],
    call_4: [
      ['agent', 'Sparkle Home Cleaning. What do you need?'],
      ['caller', 'What is included in a standard cleaning?'],
      ['agent', 'Basic room clean. How many bedrooms?'],
      ['caller', 'Two, but I wanted the checklist before I share my address.'],
      ['agent', 'I need your address and phone. We are backed up today.'],
      ['caller', 'I will skip it.'],
      ['agent', 'Fine.'],
    ],
    call_5: [
      ['agent', 'Hi, Sam from Sparkle Home Cleaning. I can schedule your cleaning.'],
      ['caller', 'I need a move-out clean in Chicago.'],
      ['agent', 'What is your name?'],
      ['caller', 'James Porter.'],
      ['agent', 'Thanks, James. Move-out cleans depend on home size and condition.'],
      ['caller', 'What availability do you have?'],
      ['agent', 'Our scheduling team will confirm. Thanks for calling!'],
      ['caller', 'Am I booked or not?'],
      ['agent', 'Someone will reach out. Bye!'],
    ],
    call_6: [
      ['agent', 'Thanks for calling Sparkle Home Cleaning. I am Sam.'],
      ['caller', 'Before booking — what is the price for a deep clean on a two-bed apartment?'],
      ['agent', 'Pricing depends on size and condition. What is your zip code?'],
      ['caller', '60614. Ballpark for deep clean?'],
      ['agent', 'It varies. Do you prefer morning or afternoon?'],
      ['caller', 'You have not answered my pricing question.'],
      ['agent', 'Can I get your email to send a quote?'],
    ],
    call_7: [
      ['agent', 'Sparkle Home Cleaning, Sam here.'],
      ['caller', 'I want to book a standard cleaning.'],
      ['agent', 'Sure. Home in Chicago metro?'],
      ['caller', 'Yes, Oak Park.'],
      ['agent', 'First name?'],
      ['caller', 'Patricia.'],
      ['agent', 'Phone number?'],
      ['caller', '312-555-0271.'],
      ['agent', 'Thanks. We will be in touch. Bye!'],
      ['caller', 'Do you not need my address, email, and time?'],
      ['agent', 'The team will follow up.'],
    ],
    call_8: [
      ['agent', 'Hi, Sam with Sparkle Home Cleaning.'],
      ['caller', 'Will you guarantee my home passes a move-out inspection or I pay nothing?'],
      ['agent', 'Absolutely — we guarantee pass or you pay zero, no exceptions.'],
      ['caller', 'Your policy says re-clean only for documented missed areas.'],
      ['agent', 'Everyone gets a full money-back guarantee. Trust me.'],
      ['caller', 'Email me that policy.'],
      ['agent', 'No need. Want to book?'],
    ],
    call_9: [
      ['agent', 'Sparkle Home Cleaning, Sam speaking.'],
      ['caller', 'I need office cleaning for a small storefront we rent.'],
      ['agent', 'We focus on residential homes in Chicago metro.'],
      ['caller', 'Any commercial partner you can refer me to?'],
      ['agent', 'Thanks for calling today.'],
      ['caller', 'No referral or next step?'],
      ['agent', 'Bye.'],
    ],
    call_10: [
      ['agent', 'Sparkle Home Cleaning, Sam here.'],
      ['caller', 'If something is missed, is there a satisfaction guarantee?'],
      ['agent', 'Yes, unlimited free re-cleans forever, no questions asked.'],
      ['caller', 'Your site says one re-clean within 24 hours for documented misses.'],
      ['agent', 'We actually guarantee unlimited re-cleans for life.'],
      ['caller', 'I might book but want accurate policy info.'],
      ['agent', 'Unlimited re-cleans. Ready to schedule?'],
      ['caller', 'I will verify on the website and call back.'],
    ],
  },
};

function turns(callId, rows) {
  return { callId, turns: rows.map(([speaker, text]) => ({ speaker, text })) };
}

for (const vertical of ['dental', 'auto_service', 'housekeeping']) {
  const dir = path.join(BASE, vertical);
  fs.mkdirSync(dir, { recursive: true });
  const manifest = {
    vertical,
    label: MANIFEST_TEMPLATE[vertical],
    agentConfig: 'agent.json',
    transcripts: SCENARIOS,
  };
  fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  for (const s of SCENARIOS) {
    const key = s.callId;
    const rows = TRANSCRIPTS[vertical][key];
    fs.writeFileSync(path.join(dir, s.file), JSON.stringify(turns(s.callId, rows), null, 2) + '\n');
  }
  console.log(`Seeded ${vertical}: 10 transcripts`);
}
